name: Windows RDP Setup

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
    - name: Enable RDP Access
      run: |
        net user runneradmin YourPassword123 /add
        net localgroup administrators runneradmin /add
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/D4Vinci/One-Liner-RDP/main/Ngrok.ps1 -OutFile ngrok.ps1
        ./ngrok.ps1 -auth "NGROK_AUTH_TOKEN" -region eu
